name: Alpine Armv7 Builder
on: [push]
env:
  NAPI_CLI_VERSION: 2.16.2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Cache build
      uses: actions/cache@v4
      with:
        save-always: true
        path: |
          build
        key: test-8
        restore-keys: |
          test-
    - run: |
        docker run -v .:/host --platform arm --network host --rm alpine:edge sh /host/build.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-artifact
        path: ./output
